package com.kongzhonghd.sts.statistics.dao;

import com.kongzhonghd.sts.statistics.model.ApiDetailLog;
import com.kongzhonghd.sts.statistics.model.ApiDetailLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ApiDetailLogMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int countByExample(ApiDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int deleteByExample(ApiDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int insert(ApiDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int insertSelective(ApiDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    List<ApiDetailLog> selectByExample(ApiDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    ApiDetailLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") ApiDetailLog record, @Param("example") ApiDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByExample(@Param("record") ApiDetailLog record, @Param("example") ApiDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByPrimaryKeySelective(ApiDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_api_performance_detail_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByPrimaryKey(ApiDetailLog record);
}