package com.kongzhonghd.sts.statistics.dao;

import com.kongzhonghd.sts.statistics.model.NetworkLog;
import com.kongzhonghd.sts.statistics.model.NetworkLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NetworkLogMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int countByExample(NetworkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int deleteByExample(NetworkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int insert(NetworkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int insertSelective(NetworkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    List<NetworkLog> selectByExample(NetworkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    NetworkLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") NetworkLog record, @Param("example") NetworkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByExample(@Param("record") NetworkLog record, @Param("example") NetworkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByPrimaryKeySelective(NetworkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsts_network_performance_log
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    int updateByPrimaryKey(NetworkLog record);
}