package com.kongzhonghd.sts.statistics.model;

import java.util.Date;

public class ApiLog
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.id
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendRequestTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long sendRequestTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveSuccessResponseTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long receiveSuccessResponseTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveErrorResponseTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long receiveErrorResponseTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double sendRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveSuccessResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double receiveSuccessResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveErrorResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double receiveErrorResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestSendRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestSendRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestReceiveSuccessResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestReceiveSuccessResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestReceiveErrorResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestReceiveErrorResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastSendRequestTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastSendRequestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastReceiveSuccessResponseTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastReceiveSuccessResponseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastReceiveErrorResponseTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastReceiveErrorResponseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.averageReceiveSuccessResponseMilliseconds
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Integer averageReceiveSuccessResponseMilliseconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveSuccessRequestTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long receiveSuccessRequestTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveErrorRequestTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long receiveErrorRequestTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendSuccessResponseTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long sendSuccessResponseTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendErrorResponseTimes
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Long sendErrorResponseTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveSuccessRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double receiveSuccessRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.receiveErrorRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double receiveErrorRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendSuccessResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double sendSuccessResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.sendErrorResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double sendErrorResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestReceiveSuccessRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestReceiveSuccessRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestReceiveErrorRequestThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestReceiveErrorRequestThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestSendSuccessResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestSendSuccessResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.largestSendErrorResponseThroughput
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Double largestSendErrorResponseThroughput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastReceiveSuccessRequestTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastReceiveSuccessRequestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastReceiveErrorRequestTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastReceiveErrorRequestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastSendSuccessResponseTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastSendSuccessResponseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.lastSendErrorResponseTime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date lastSendErrorResponseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.averageSendSuccessResponseMilliseconds
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Integer averageSendSuccessResponseMilliseconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.IPAddr
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private String IPAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_api_performance_log.logtime
     *
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    private Date logtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.id
     *
     * @return the value of tsts_api_performance_log.id
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getId()
    {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.id
     *
     * @param id the value for tsts_api_performance_log.id
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendRequestTimes
     *
     * @return the value of tsts_api_performance_log.sendRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getSendRequestTimes()
    {
        return sendRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendRequestTimes
     *
     * @param sendRequestTimes the value for tsts_api_performance_log.sendRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendRequestTimes(Long sendRequestTimes)
    {
        this.sendRequestTimes = sendRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveSuccessResponseTimes
     *
     * @return the value of tsts_api_performance_log.receiveSuccessResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getReceiveSuccessResponseTimes()
    {
        return receiveSuccessResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveSuccessResponseTimes
     *
     * @param receiveSuccessResponseTimes the value for tsts_api_performance_log.receiveSuccessResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveSuccessResponseTimes(Long receiveSuccessResponseTimes)
    {
        this.receiveSuccessResponseTimes = receiveSuccessResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveErrorResponseTimes
     *
     * @return the value of tsts_api_performance_log.receiveErrorResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getReceiveErrorResponseTimes()
    {
        return receiveErrorResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveErrorResponseTimes
     *
     * @param receiveErrorResponseTimes the value for tsts_api_performance_log.receiveErrorResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveErrorResponseTimes(Long receiveErrorResponseTimes)
    {
        this.receiveErrorResponseTimes = receiveErrorResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendRequestThroughput
     *
     * @return the value of tsts_api_performance_log.sendRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getSendRequestThroughput()
    {
        return sendRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendRequestThroughput
     *
     * @param sendRequestThroughput the value for tsts_api_performance_log.sendRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendRequestThroughput(Double sendRequestThroughput)
    {
        this.sendRequestThroughput = sendRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveSuccessResponseThroughput
     *
     * @return the value of tsts_api_performance_log.receiveSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getReceiveSuccessResponseThroughput()
    {
        return receiveSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveSuccessResponseThroughput
     *
     * @param receiveSuccessResponseThroughput
     *         the value for tsts_api_performance_log.receiveSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveSuccessResponseThroughput(Double receiveSuccessResponseThroughput)
    {
        this.receiveSuccessResponseThroughput = receiveSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveErrorResponseThroughput
     *
     * @return the value of tsts_api_performance_log.receiveErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getReceiveErrorResponseThroughput()
    {
        return receiveErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveErrorResponseThroughput
     *
     * @param receiveErrorResponseThroughput the value for tsts_api_performance_log.receiveErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveErrorResponseThroughput(Double receiveErrorResponseThroughput)
    {
        this.receiveErrorResponseThroughput = receiveErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestSendRequestThroughput
     *
     * @return the value of tsts_api_performance_log.largestSendRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestSendRequestThroughput()
    {
        return largestSendRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestSendRequestThroughput
     *
     * @param largestSendRequestThroughput the value for tsts_api_performance_log.largestSendRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestSendRequestThroughput(Double largestSendRequestThroughput)
    {
        this.largestSendRequestThroughput = largestSendRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestReceiveSuccessResponseThroughput
     *
     * @return the value of tsts_api_performance_log.largestReceiveSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestReceiveSuccessResponseThroughput()
    {
        return largestReceiveSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestReceiveSuccessResponseThroughput
     *
     * @param largestReceiveSuccessResponseThroughput
     *         the value for tsts_api_performance_log.largestReceiveSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestReceiveSuccessResponseThroughput(Double largestReceiveSuccessResponseThroughput)
    {
        this.largestReceiveSuccessResponseThroughput = largestReceiveSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestReceiveErrorResponseThroughput
     *
     * @return the value of tsts_api_performance_log.largestReceiveErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestReceiveErrorResponseThroughput()
    {
        return largestReceiveErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestReceiveErrorResponseThroughput
     *
     * @param largestReceiveErrorResponseThroughput
     *         the value for tsts_api_performance_log.largestReceiveErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestReceiveErrorResponseThroughput(Double largestReceiveErrorResponseThroughput)
    {
        this.largestReceiveErrorResponseThroughput = largestReceiveErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastSendRequestTime
     *
     * @return the value of tsts_api_performance_log.lastSendRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastSendRequestTime()
    {
        return lastSendRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastSendRequestTime
     *
     * @param lastSendRequestTime the value for tsts_api_performance_log.lastSendRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastSendRequestTime(Date lastSendRequestTime)
    {
        this.lastSendRequestTime = lastSendRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastReceiveSuccessResponseTime
     *
     * @return the value of tsts_api_performance_log.lastReceiveSuccessResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastReceiveSuccessResponseTime()
    {
        return lastReceiveSuccessResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastReceiveSuccessResponseTime
     *
     * @param lastReceiveSuccessResponseTime the value for tsts_api_performance_log.lastReceiveSuccessResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastReceiveSuccessResponseTime(Date lastReceiveSuccessResponseTime)
    {
        this.lastReceiveSuccessResponseTime = lastReceiveSuccessResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastReceiveErrorResponseTime
     *
     * @return the value of tsts_api_performance_log.lastReceiveErrorResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastReceiveErrorResponseTime()
    {
        return lastReceiveErrorResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastReceiveErrorResponseTime
     *
     * @param lastReceiveErrorResponseTime the value for tsts_api_performance_log.lastReceiveErrorResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastReceiveErrorResponseTime(Date lastReceiveErrorResponseTime)
    {
        this.lastReceiveErrorResponseTime = lastReceiveErrorResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.averageReceiveSuccessResponseMilliseconds
     *
     * @return the value of tsts_api_performance_log.averageReceiveSuccessResponseMilliseconds
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Integer getAverageReceiveSuccessResponseMilliseconds()
    {
        return averageReceiveSuccessResponseMilliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.averageReceiveSuccessResponseMilliseconds
     *
     * @param averageReceiveSuccessResponseMilliseconds
     *         the value for tsts_api_performance_log.averageReceiveSuccessResponseMilliseconds
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setAverageReceiveSuccessResponseMilliseconds(Integer averageReceiveSuccessResponseMilliseconds)
    {
        this.averageReceiveSuccessResponseMilliseconds = averageReceiveSuccessResponseMilliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveSuccessRequestTimes
     *
     * @return the value of tsts_api_performance_log.receiveSuccessRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getReceiveSuccessRequestTimes()
    {
        return receiveSuccessRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveSuccessRequestTimes
     *
     * @param receiveSuccessRequestTimes the value for tsts_api_performance_log.receiveSuccessRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveSuccessRequestTimes(Long receiveSuccessRequestTimes)
    {
        this.receiveSuccessRequestTimes = receiveSuccessRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveErrorRequestTimes
     *
     * @return the value of tsts_api_performance_log.receiveErrorRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getReceiveErrorRequestTimes()
    {
        return receiveErrorRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveErrorRequestTimes
     *
     * @param receiveErrorRequestTimes the value for tsts_api_performance_log.receiveErrorRequestTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveErrorRequestTimes(Long receiveErrorRequestTimes)
    {
        this.receiveErrorRequestTimes = receiveErrorRequestTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendSuccessResponseTimes
     *
     * @return the value of tsts_api_performance_log.sendSuccessResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getSendSuccessResponseTimes()
    {
        return sendSuccessResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendSuccessResponseTimes
     *
     * @param sendSuccessResponseTimes the value for tsts_api_performance_log.sendSuccessResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendSuccessResponseTimes(Long sendSuccessResponseTimes)
    {
        this.sendSuccessResponseTimes = sendSuccessResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendErrorResponseTimes
     *
     * @return the value of tsts_api_performance_log.sendErrorResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Long getSendErrorResponseTimes()
    {
        return sendErrorResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendErrorResponseTimes
     *
     * @param sendErrorResponseTimes the value for tsts_api_performance_log.sendErrorResponseTimes
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendErrorResponseTimes(Long sendErrorResponseTimes)
    {
        this.sendErrorResponseTimes = sendErrorResponseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveSuccessRequestThroughput
     *
     * @return the value of tsts_api_performance_log.receiveSuccessRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getReceiveSuccessRequestThroughput()
    {
        return receiveSuccessRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveSuccessRequestThroughput
     *
     * @param receiveSuccessRequestThroughput
     *         the value for tsts_api_performance_log.receiveSuccessRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveSuccessRequestThroughput(Double receiveSuccessRequestThroughput)
    {
        this.receiveSuccessRequestThroughput = receiveSuccessRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.receiveErrorRequestThroughput
     *
     * @return the value of tsts_api_performance_log.receiveErrorRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getReceiveErrorRequestThroughput()
    {
        return receiveErrorRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.receiveErrorRequestThroughput
     *
     * @param receiveErrorRequestThroughput the value for tsts_api_performance_log.receiveErrorRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setReceiveErrorRequestThroughput(Double receiveErrorRequestThroughput)
    {
        this.receiveErrorRequestThroughput = receiveErrorRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendSuccessResponseThroughput
     *
     * @return the value of tsts_api_performance_log.sendSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getSendSuccessResponseThroughput()
    {
        return sendSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendSuccessResponseThroughput
     *
     * @param sendSuccessResponseThroughput the value for tsts_api_performance_log.sendSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendSuccessResponseThroughput(Double sendSuccessResponseThroughput)
    {
        this.sendSuccessResponseThroughput = sendSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.sendErrorResponseThroughput
     *
     * @return the value of tsts_api_performance_log.sendErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getSendErrorResponseThroughput()
    {
        return sendErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.sendErrorResponseThroughput
     *
     * @param sendErrorResponseThroughput the value for tsts_api_performance_log.sendErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setSendErrorResponseThroughput(Double sendErrorResponseThroughput)
    {
        this.sendErrorResponseThroughput = sendErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestReceiveSuccessRequestThroughput
     *
     * @return the value of tsts_api_performance_log.largestReceiveSuccessRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestReceiveSuccessRequestThroughput()
    {
        return largestReceiveSuccessRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestReceiveSuccessRequestThroughput
     *
     * @param largestReceiveSuccessRequestThroughput
     *         the value for tsts_api_performance_log.largestReceiveSuccessRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestReceiveSuccessRequestThroughput(Double largestReceiveSuccessRequestThroughput)
    {
        this.largestReceiveSuccessRequestThroughput = largestReceiveSuccessRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestReceiveErrorRequestThroughput
     *
     * @return the value of tsts_api_performance_log.largestReceiveErrorRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestReceiveErrorRequestThroughput()
    {
        return largestReceiveErrorRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestReceiveErrorRequestThroughput
     *
     * @param largestReceiveErrorRequestThroughput
     *         the value for tsts_api_performance_log.largestReceiveErrorRequestThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestReceiveErrorRequestThroughput(Double largestReceiveErrorRequestThroughput)
    {
        this.largestReceiveErrorRequestThroughput = largestReceiveErrorRequestThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestSendSuccessResponseThroughput
     *
     * @return the value of tsts_api_performance_log.largestSendSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestSendSuccessResponseThroughput()
    {
        return largestSendSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestSendSuccessResponseThroughput
     *
     * @param largestSendSuccessResponseThroughput
     *         the value for tsts_api_performance_log.largestSendSuccessResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestSendSuccessResponseThroughput(Double largestSendSuccessResponseThroughput)
    {
        this.largestSendSuccessResponseThroughput = largestSendSuccessResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.largestSendErrorResponseThroughput
     *
     * @return the value of tsts_api_performance_log.largestSendErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Double getLargestSendErrorResponseThroughput()
    {
        return largestSendErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.largestSendErrorResponseThroughput
     *
     * @param largestSendErrorResponseThroughput
     *         the value for tsts_api_performance_log.largestSendErrorResponseThroughput
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLargestSendErrorResponseThroughput(Double largestSendErrorResponseThroughput)
    {
        this.largestSendErrorResponseThroughput = largestSendErrorResponseThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastReceiveSuccessRequestTime
     *
     * @return the value of tsts_api_performance_log.lastReceiveSuccessRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastReceiveSuccessRequestTime()
    {
        return lastReceiveSuccessRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastReceiveSuccessRequestTime
     *
     * @param lastReceiveSuccessRequestTime the value for tsts_api_performance_log.lastReceiveSuccessRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastReceiveSuccessRequestTime(Date lastReceiveSuccessRequestTime)
    {
        this.lastReceiveSuccessRequestTime = lastReceiveSuccessRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastReceiveErrorRequestTime
     *
     * @return the value of tsts_api_performance_log.lastReceiveErrorRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastReceiveErrorRequestTime()
    {
        return lastReceiveErrorRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastReceiveErrorRequestTime
     *
     * @param lastReceiveErrorRequestTime the value for tsts_api_performance_log.lastReceiveErrorRequestTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastReceiveErrorRequestTime(Date lastReceiveErrorRequestTime)
    {
        this.lastReceiveErrorRequestTime = lastReceiveErrorRequestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastSendSuccessResponseTime
     *
     * @return the value of tsts_api_performance_log.lastSendSuccessResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastSendSuccessResponseTime()
    {
        return lastSendSuccessResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastSendSuccessResponseTime
     *
     * @param lastSendSuccessResponseTime the value for tsts_api_performance_log.lastSendSuccessResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastSendSuccessResponseTime(Date lastSendSuccessResponseTime)
    {
        this.lastSendSuccessResponseTime = lastSendSuccessResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.lastSendErrorResponseTime
     *
     * @return the value of tsts_api_performance_log.lastSendErrorResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLastSendErrorResponseTime()
    {
        return lastSendErrorResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.lastSendErrorResponseTime
     *
     * @param lastSendErrorResponseTime the value for tsts_api_performance_log.lastSendErrorResponseTime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLastSendErrorResponseTime(Date lastSendErrorResponseTime)
    {
        this.lastSendErrorResponseTime = lastSendErrorResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.averageSendSuccessResponseMilliseconds
     *
     * @return the value of tsts_api_performance_log.averageSendSuccessResponseMilliseconds
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Integer getAverageSendSuccessResponseMilliseconds()
    {
        return averageSendSuccessResponseMilliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.averageSendSuccessResponseMilliseconds
     *
     * @param averageSendSuccessResponseMilliseconds
     *         the value for tsts_api_performance_log.averageSendSuccessResponseMilliseconds
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setAverageSendSuccessResponseMilliseconds(Integer averageSendSuccessResponseMilliseconds)
    {
        this.averageSendSuccessResponseMilliseconds = averageSendSuccessResponseMilliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.IPAddr
     *
     * @return the value of tsts_api_performance_log.IPAddr
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public String getIPAddr()
    {
        return IPAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.IPAddr
     *
     * @param IPAddr the value for tsts_api_performance_log.IPAddr
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setIPAddr(String IPAddr)
    {
        this.IPAddr = IPAddr == null ? null : IPAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_api_performance_log.logtime
     *
     * @return the value of tsts_api_performance_log.logtime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public Date getLogtime()
    {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_api_performance_log.logtime
     *
     * @param logtime the value for tsts_api_performance_log.logtime
     * @mbggenerated Thu Aug 08 17:52:21 CST 2013
     */
    public void setLogtime(Date logtime)
    {
        this.logtime = logtime;
    }
}