package com.kongzhonghd.sts.statistics.model;

import java.util.Date;

public class TstsThreadpoolPerformanceLog
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.id
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.name
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.corePoolSize
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Integer corepoolsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.maximumPoolSize
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Integer maximumpoolsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.largestPoolSize
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Integer largestpoolsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.poolSize
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Integer poolsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.activeCount
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Integer activecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.completedTaskCount
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Long completedtaskcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.taskCount
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Long taskcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.IPAddr
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsts_threadPool_performance_log.logtime
     *
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    private Date logtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.id
     *
     * @return the value of tsts_threadPool_performance_log.id
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Long getId()
    {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.id
     *
     * @param id the value for tsts_threadPool_performance_log.id
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.name
     *
     * @return the value of tsts_threadPool_performance_log.name
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public String getName()
    {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.name
     *
     * @param name the value for tsts_threadPool_performance_log.name
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.corePoolSize
     *
     * @return the value of tsts_threadPool_performance_log.corePoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Integer getCorepoolsize()
    {
        return corepoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.corePoolSize
     *
     * @param corepoolsize the value for tsts_threadPool_performance_log.corePoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setCorepoolsize(Integer corepoolsize)
    {
        this.corepoolsize = corepoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.maximumPoolSize
     *
     * @return the value of tsts_threadPool_performance_log.maximumPoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Integer getMaximumpoolsize()
    {
        return maximumpoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.maximumPoolSize
     *
     * @param maximumpoolsize the value for tsts_threadPool_performance_log.maximumPoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setMaximumpoolsize(Integer maximumpoolsize)
    {
        this.maximumpoolsize = maximumpoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.largestPoolSize
     *
     * @return the value of tsts_threadPool_performance_log.largestPoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Integer getLargestpoolsize()
    {
        return largestpoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.largestPoolSize
     *
     * @param largestpoolsize the value for tsts_threadPool_performance_log.largestPoolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setLargestpoolsize(Integer largestpoolsize)
    {
        this.largestpoolsize = largestpoolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.poolSize
     *
     * @return the value of tsts_threadPool_performance_log.poolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Integer getPoolsize()
    {
        return poolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.poolSize
     *
     * @param poolsize the value for tsts_threadPool_performance_log.poolSize
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setPoolsize(Integer poolsize)
    {
        this.poolsize = poolsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.activeCount
     *
     * @return the value of tsts_threadPool_performance_log.activeCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Integer getActivecount()
    {
        return activecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.activeCount
     *
     * @param activecount the value for tsts_threadPool_performance_log.activeCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setActivecount(Integer activecount)
    {
        this.activecount = activecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.completedTaskCount
     *
     * @return the value of tsts_threadPool_performance_log.completedTaskCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Long getCompletedtaskcount()
    {
        return completedtaskcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.completedTaskCount
     *
     * @param completedtaskcount the value for tsts_threadPool_performance_log.completedTaskCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setCompletedtaskcount(Long completedtaskcount)
    {
        this.completedtaskcount = completedtaskcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.taskCount
     *
     * @return the value of tsts_threadPool_performance_log.taskCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Long getTaskcount()
    {
        return taskcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.taskCount
     *
     * @param taskcount the value for tsts_threadPool_performance_log.taskCount
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setTaskcount(Long taskcount)
    {
        this.taskcount = taskcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.IPAddr
     *
     * @return the value of tsts_threadPool_performance_log.IPAddr
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public String getIpaddr()
    {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.IPAddr
     *
     * @param ipaddr the value for tsts_threadPool_performance_log.IPAddr
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setIpaddr(String ipaddr)
    {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsts_threadPool_performance_log.logtime
     *
     * @return the value of tsts_threadPool_performance_log.logtime
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public Date getLogtime()
    {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsts_threadPool_performance_log.logtime
     *
     * @param logtime the value for tsts_threadPool_performance_log.logtime
     * @mbggenerated Wed Aug 28 16:19:38 CST 2013
     */
    public void setLogtime(Date logtime)
    {
        this.logtime = logtime;
    }
}